### ISSUE TITLE
WTF Tweaks ignoring dirt & cobblestone gravity setting

### ISSUE THREAD

**Issue by rckymtnrfc** [WhiskyTangoFawks/WTFTweaks#1]
I have the following in my config on both the server and client.  Dirt and Cobble continue to call in SMP and SSP.

gravity {
    B:"Cobblestone falls when disturbed"=false
    B:"Dirt falls when disturbed"=false
    B:"Enable damage from falling cobblestone and dirt"=false
}

**Comment by WhiskyTangoFawks** [comment]
Looks like it got screwed up when I redid my dev environment.  I've been meaning to change the config option to support adding blocks anyway, I'll try to get a fix out shortly for testing.

**Comment by WhiskyTangoFawks** [comment]
I've changed the config to an list of enabled blocks in the latest release.
