### ISSUE TITLE
buildcraft Quarry 'null point exeption'

### ISSUE THREAD

**Issue by Labna** [WhiskyTangoFawks/WTFTweaks#8]
Hi,
I'm using BuildCraft and it crash at the moment the quarry break block, I'm on mincraft 1.7.10, WTFCore 1.66, WTFTweaks 1.28, Buildcraft 7.1.18.
I post here cause the top stack talk about WTFtweaks.

> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 22/10/16 20:26
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
>   at wtftweaks.util.WTFEventMonitor.BlockBreakEvent(WTFEventMonitor.java:122)
>   at >cpw.mods.fml.common.eventhandler.ASMEventHandler_711_WTFEventMonitor_BlockBreakEvent_BreakEvent.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at buildcraft.core.lib.utils.BlockMiner.acceptEnergy(BlockMiner.java:97)
>   at buildcraft.builders.TileQuarry.dig(TileQuarry.java:250)
>   at buildcraft.builders.TileQuarry.func_145845_h(TileQuarry.java:204)
>   at net.minecraft.world.World.func_72939_s(World.java:1939)
>   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at wtftweaks.util.WTFEventMonitor.BlockBreakEvent(WTFEventMonitor.java:122)
>   at >cpw.mods.fml.common.eventhandler.ASMEventHandler_711_WTFEventMonitor_BlockBreakEvent_BreakEvent.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at buildcraft.core.lib.utils.BlockMiner.acceptEnergy(BlockMiner.java:97)
>   at buildcraft.builders.TileQuarry.dig(TileQuarry.java:250)
>   at buildcraft.builders.TileQuarry.func_145845_h(TileQuarry.java:204)
> 
> -- Block entity being ticked --
> Details:
>   Name: Machine // buildcraft.builders.TileQuarryCompat
>   Block type: ID #1810 (tile.machineBlock // buildcraft.builders.BlockQuarryCompat)
>   Block data value: 5 / 0x5 / 0b0101
>   Block location: World: (1856,111,1573), Chunk: (at 0,6,5 in 116,98; contains blocks 1856,0,1568 to 1871,255,1583), Region: (3,3; contains chunks 96,96 to 127,127, blocks 1536,0,1536 to 2047,255,2047)
>   Actual block type: ID #1810 (tile.machineBlock // buildcraft.builders.BlockQuarryCompat)
>   Actual block data value: 5 / 0x5 / 0b0101
> Stacktrace:
>   at net.minecraft.world.World.func_72939_s(World.java:1939)
>   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
> 
> -- Affected level --
> Details:
>   Level name: 0
>   All players: 0 total; []
>   Chunk stats: ServerChunkCache: 2 Drop: 2
>   Level seed: 2629207911344102102
>   Level generator: ID 00 - default, ver 1. Features enabled: false
>   Level generator options: 
>   Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), >Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>   Level time: 0 game time, 0 day time
>   Level dimension: 0
>   Level storage version: 0x00000 - Unknown?
>   Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
>   Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> 
>   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.7.10
>   Operating System: Linux (amd64) version 3.16.0-4-amd64
>   Java Version: 1.8.0_91, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 100175528 bytes (95 MB) / 665985024 bytes (635 MB) up to 2130051072 bytes (2031 MB)
>   JVM Flags: 9 total; -Xms256m -Xmx2G -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseConcMarkSweepGC
>   AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   IntCache: cache: 0, tcache: 47671, allocated: 0, tallocated: 4096
>   FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 168 mods loaded, 168 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
>   UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
>   UCHIJAAAA   AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
>   UCHIJAAAA   Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
>   UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
>   UCHIJAAAA   itemphysic{1.1.5} [ItemPhysic](minecraft.jar) 
>   UCHIJAAAA   MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
>   UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
>   UCHIJAAAA   OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) 
>   UCHIJAAAA   PlayerAPI{1.4} [Player API](minecraft.jar) 
>   UCHIJAAAA   VeinMiner_coremod{0.26.0_build.unknown} [Core mod](minecraft.jar) 
>   UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
>   UCHIJAAAA   mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) 
>   UCHIJAAAA   debug{1.0} [debug](denseores-1.6.2.jar) 
>   UCHIJAAAA   gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar) 
>   UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
>   UCHIJAAAA   arsmagica2{1.4.0.009} [Ars Magica 2](1.7.10_AM2-1.4.0.009.jar) 
>   UCHIJAAAA   powerGems{0.3.0} [Power Gems]([1.7.10]PowerGems 0.4.5.jar.zip) 
>   UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
>   UCHIJAAAA   Enchiridion{1.3} [Enchiridion](Enchiridion 2-1.7.10-2.0.2a.jar) 
>   UCHIJAAAA   adventurersamulets{1.7.10-1.5.0c} [Adventurer's Amulets](AdventurersAmulets-1.7.10-1.5.0c.jar) 
>   UCHIJAAAA   aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar) 
>   UCHIJAAAA   koresample{1.7.10-1.3.2} [Kore Sample](KoreSample-1.7.10-1.3.2.jar) 
>   UCHIJAAAA   dendrology{1.7.10-1.6.4} [Ancient Trees](AncientTrees-1.7.10-1.6.4.jar) 
>   UCHIJAAAA   antiqueatlas{1.7.10-4.2.10} [Antique Atlas](antiqueatlas-1.7.10-4.2.10.jar) 
>   UCHIJAAAA   AppleCore{1.3.1} [AppleCore](AppleCore-mc1.7.10-1.3.1.jar) 
>   UCHIJAAAA   armourersWorkshop{1.7.10-0.42.2} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.42.2.jar) 
>   UCHIJAAAA   CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
>   UCHIJAAAA   ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.5-115.jar) 
>   UCHIJAAAA   ForgeMultipart{1.2.0.347} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
>   UCHIJAAAA   BuildCraft|Core{7.1.18} [BuildCraft](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
>   UCHIJAAAA   Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
>   UCHIJAAAA   ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
>   UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
>   UCHIJAAAA   ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.4-247.jar) 
>   UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
>   UCHIJAAAA   Armory{1.1.0.1-260} [Armory](Armory-1.1.0.1-260.jar) 
>   UCHIJAAAA   Armory-World{@VERSION@} [Armory-World](Armory-World-1.0.0-21.jar) 
>   UCHIJAAAA   Armory-Weaponry{@VERSION@} [Armory-Weaponry](Armory-Weaponry-1.0.0-20.jar) 
>   UCHIJAAAA   plushieWrapper{0.0.0} [Plushie Wrapper](Armourers-Workshop-1.7.10-0.42.2.jar) 
>   UCHIJAAAA   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
>   UCHIJAAAA   AromaBackup{0.1.0.0} [AromaBackup](AromaBackup-1.7.10-0.1.0.0.jar) 
>   UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.1.0.0.jar) 
>   UCHIJAAAA   ATG{0.10.0} [Alternate Terrain Generation](ATG%28Alternate Terrain Generation%29-1.7.10-0.12.0.jar) 
>   UCHIJAAAA   BrandonsCore{1.0.0.12} [Brandon's Core](BrandonsCore-1.0.0.12.jar) 
>   UCHIJAAAA   BuildCraft|Transport{7.1.18} [BC Transport](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   BuildCraft|Silicon{7.1.18} [BC Silicon](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   BuildCraft|Energy{7.1.18} [BC Energy](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   BuildCraft|Factory{7.1.18} [BC Factory](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   BuildCraft|Builders{7.1.18} [BC Builders](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   BuildCraft|Robotics{7.1.18} [BC Robotics](buildcraft-7.1.18.jar) 
>   UCHIJAAAA   BuildCraft|Compat{7.1.5} [BuildCraft Compat](buildcraft-compat-7.1.5.jar) 
>   UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
>   UCHIJAAAA   chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
>   UCHIJAAAA   cookiecore{1.4.0} [Cookie Core](CookieCore-1.7.10-1.4.0-11.jar) 
>   UCHIJAAAA   BuildMod{v1.0} [Build Mod](coroutil-1.7.10-1.1.5.jar) 
>   UCHIJAAAA   CoroPets{v1.0} [CoroPets](coroutil-1.7.10-1.1.5.jar) 
>   UCHIJAAAA   CoroAI{v1.0} [CoroAI](coroutil-1.7.10-1.1.5.jar) 
>   UCHIJAAAA   ExtendedRenderer{v1.0} [Extended Renderer](coroutil-1.7.10-1.1.5.jar) 
>   UCHIJAAAA   ConfigMod{v1.0} [Extended Mod Config](coroutil-1.7.10-1.1.5.jar) 
>   UCHIJAAAA   creativecore{1.3.14} [CreativeCore](CreativeCore v1.3.24 mc1.7.10.jar) 
>   UCHIJAAAA   CustomOreGen{1.2.24} [Custom Ore Generation](CustomOreGen-1.7.10-1.2.24.jar) 
>   UCHIJAAAA   DraconicEvolution{1.0.2h} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2h.jar) 
>   UCHIJAAAA   dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar.zip) 
>   UCHIJAAAA   Enchiridion2{2.0.2a} [Enchiridion 2](Enchiridion 2-1.7.10-2.0.2a.jar) 
>   UCHIJAAAA   endercore{1.7.10-0.2.0.39_beta} [EnderCore](EnderCore-1.7.10-0.2.0.39_beta.jar) 
>   UCHIJAAAA   MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) 
>   UCHIJAAAA   Mekanism{9.1.0} [Mekanism](Mekanism-1.7.10-9.1.0.281.jar) 
>   UCHIJAAAA   EnderIO{1.7.10-2.2.8.367} [Ender IO](EnderIO-1.7.10-2.2.8.367.jar) 
>   UCHIJAAAA   enviromine{1.3.119} [EnviroMine](EnviroMine-1.3.119.jar) 
>   UCHIJAAAA   ESM{10.0.122} [Epic Siege Mod](EpicSiegeMod-10.0.122.jar) 
>   UCHIJAAAA   etfuturum{1.5.2} [Et Futurum](Et Futurum-1.5.2.jar) 
>   UCHIJAAAA   Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) 
>   UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
>   UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
>   UCHIJAAAA   TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks](TSteelworks-1.7.10-1.1.2-20.jar) 
>   UCHIJAAAA   ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) 
>   UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
>   UCHIJAAAA   fastleafdecay{1.4} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.4.jar) 
>   UCHIJAAAA   fluxedcrystals{1.0.3} [Fluxed-Crystals](fluxedCrystals-1.0.3.jar) 
>   UCHIJAAAA   GardenContainers{1.7.10-1.7.0} [Garden Containers](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GardenCore{1.7.10-1.7.0} [Garden Core](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GardenStuff{1.7.10-1.7.0} [Garden Stuff](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GardenTrees{1.7.10-1.7.0} [Garden Trees](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   wuppy29_goblingiant{1.0.4.3} [Goblins and Giants](Goblins and Giants 1.7.10-1.0.4.3.jar) 
>   UCHIJAAAA   GraveStone{2.16.1} [GraveStone](GraveStone-2.16.1.jar) 
>   UCHIJAAAA   HardcoreQuesting{4.4.4} [Hardcore Questing Mode](HQM-The Journey-4.4.4.jar) 
>   UCHIJAAAA   iChunUtil{4.2.3} [iChunUtil](iChunUtil-4.2.3.jar) 
>   UCHIJAAAA   immersiveintegration{0.6.8} [Immersive Integration](immersiveintegration-0.6.8.jar) 
>   UCHIJAAAA   infiniteinvo{1.0.52} [InfiniteInvo](InfiniteInvo-1.0.52.jar) 
>   UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
>   UCHIJAAAA   IrishLuck{1.7.10-0.0.8} [Irish Luck](IrishLuck-1.7.10-0.0.8.jar) 
>   UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
>   UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
>   UCHIJAAAA   JASCompatability{1.2.0} [Just Another Spawner Compatibility Addon](JustAnotherSpawnerCompatibilityAddon-1.2.0.jar) 
>   UCHIJAAAA   LatCoreMC{1.6.11} [LatCoreMC](LatCoreMC-1.7.10-1.6.11.1.jar) 
>   UCHIJAAAA   LatBlocks{1.6.11} [LatBlocks](LatBlocks-1.7.10-1.6.11.1.jar) 
>   UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
>   UCHIJAAAA   LookingGlass{0.2.0.01} [Looking Glass](LookingGlass-1.7.10-0.2.0.01.jar) 
>   UCHIJAAAA   LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
>   UCHIJAAAA   malisiscore{1.7.10-0.14.3} [MalisisCore](malisiscore-1.7.10-0.14.3.jar) 
>   UCHIJAAAA   malisisdoors{1.7.10-1.13.2} [Malisis' Doors](malisisdoors-1.7.10-1.13.2.jar) 
>   UCHIJAAAA   RadixCore{2.1.3} [RadixCore](RadixCore-1.7.10-2.1.3-universal.jar) 
>   UCHIJAAAA   MCA{1.7.10-5.2.2} [Minecraft Comes Alive](MCA-1.7.10-5.2.2-universal.jar) 
>   UCHIJAAAA   MekanismGenerators{9.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-9.1.0.281.jar) 
>   UCHIJAAAA   MekanismTools{9.1.0} [MekanismTools](MekanismTools-1.7.10-9.1.0.281.jar) 
>   UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.7.10-1.9.jar) 
>   UCHIJAAAA   MobAmputation{4.0.1} [MobAmputation](MobAmputation-4.0.1.jar) 
>   UCHIJAAAA   MobDismemberment{4.0.0} [MobDismemberment](MobDismemberment-4.0.0.jar) 
>   UCHIJAAAA   modtweaker2{0.9.5} [Mod Tweaker 2](ModTweaker2-0.9.5.jar) 
>   UCHIJAAAA   Morph{0.9.3} [Morph](Morph-Beta-0.9.3.jar) 
>   UCHIJAAAA   Morpheus{1.7.10-1.6.10} [Morpheus](Morpheus-1.7.10-1.6.10.jar) 
>   UCHIJAAAA   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
>   UCHIJAAAA   neiintegration{1.1.1} [NEI Integration](NEIIntegration-MC1.7.10-1.1.1.jar) 
>   UCHIJAAAA   neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](NotEnoughResources-1.7.10-0.1.0-122.jar) 
>   UCHIJAAAA   ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
>   UCHIJAAAA   MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
>   UCHIJAAAA   Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
>   UCHIJAAAA   PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) 
>   UCHIJAAAA   reciperesearch{1.0.22} [RecipeResearch](RecipeResearch-1.0.22.jar) 
>   UCHIJAAAA   corerm{1.0c} [RikMuld's Core](RikMuldsCore_1.0c.jar) 
>   UCHIJAAAA   AS_Ruins{14.8} [Ruins Spawning System](Ruins-1.7.10.jar) 
>   UCHIJAAAA   scottstweaks{1.7.10-1.3.1} [Scott's Tweaks](ScottsTweaks-1.7.10-1.3.1.jar) 
>   UCHIJAAAA   secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.413.jar) 
>   UCHIJAAAA   punt{1.7.10-10.13.0-14.0} [Punt](Small-Boats-Mod-1.7.10.jar) 
>   UCHIJAAAA   whitehall{1.7.10-10.13.0-14.0} [Whitehall](Small-Boats-Mod-1.7.10.jar) 
>   UCHIJAAAA   hoy{1.7.10-10.13.0-14.0} [Hoy](Small-Boats-Mod-1.7.10.jar) 
>   UCHIJAAAA   smallboats{1.7.10-10.13.0-14.0} [SmallBoats (base)](Small-Boats-Mod-1.7.10.jar) 
>   UCHIJAAAA   SmartRender{2.1} [Smart Render](SmartRender-1.7.10-2.1.jar) 
>   UCHIJAAAA   redgear_core{2.1.3} [Red Gear Core](RedGearCore-1.7.10-2.1.3.jar) 
>   UCHIJAAAA   redgear_snowfall{2.2.2} [Snowfall](Snowfall-1.7.10-2.2.2.jar) 
>   UCHIJAAAA   SolarExpansion{1.6a} [Solar Expansion](SolarExpansion-Basic-1.6a.jar) 
>   UCHIJAAAA   SpiceOfLife{1.3.1} [The Spice of Life](SpiceOfLife-mc1.7.10-1.3.1.jar) 
>   UCHIJAAAA   Sync{4.0.1} [Sync](Sync-4.0.1.jar) 
>   UCHIJAAAA   TextureGeneratorLib{0.2} [TextureGeneratorLib](TextureGeneratorLib-1.7.10_vBeta2.jar) 
>   UCHIJAAAA   camping{2.1g} [The Camping Mod 2](TheCampingMod_2.1g.jar) 
>   UCHIJAAAA   ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
>   UCHIJAAAA   ThermalSmeltery{1.0} [Thermal Smeltery](ThermalSmeltery-1.3.1.4.jar) 
>   UCHIJAAAA   throwabletorchmod{1.3} [ThrowableTorchMod](ThrowableTorchMod-1.7.10-1.3.jar) 
>   UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
>   UCHIJAAAA   um_tmodifiers{1.2.1} [Tinkers' Modifiers](Tinkers' Modifiers v1.2.1.jar) 
>   UCHIJAAAA   TMechworks{0.2.15.106} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.15.106.jar) 
>   UCHIJAAAA   TooManyGodDamnOres{${version}} [TooManyGodDamnOres](TooManyGodDamnOres-1.7.2-10.12.2.1147_1.4.0-4.jar) 
>   UCHIJAAAA   Torcherino{2.2s} [Torcherino](Torcherino-1.7.10-2.2s.jar) 
>   UCHIJAAAA   Translocator{1.1.2.15} [Translocator](Translocator-1.7.10-1.1.2.15-universal.jar) 
>   UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
>   UCHIJAAAA   UndergroundBiomes{0.7} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.7.jar) 
>   UCHIJAAAA   UtilityMobs{3.1.1} [Utility Mobs](UtilityMobs-1.7.10-3.1.1.jar) 
>   UCHIJAAAA   VeinMiner{0.26.0_build.unknown} [Vein Miner](Vein-Miner-Mod-1.7.10.jar) 
>   UCHIJAAAA   VeinMinerModSupport{0.26.0_build.unknown} [Mod Support](Vein-Miner-Mod-1.7.10.jar) 
>   UCHIJAAAA   WTFCore{1.65} [WhiskyTangoFox's Core](WTFCore-1.7.10_v1.66.jar) 
>   UCHIJAAAA   WTFTweaks{1.28} [WhiskyTangoFox's Tweaks](WTFTweaks-1.7.10_v1.28.jar) 
>   UCHIJAAAA   xact{0.5.2} [XACT](XACT-1.7.10-0.5.2d.jar) 
>   UCHIJAAAA   ZAMod{v1.10} [Zombie Awareness](zombieawareness-1.7.10-1.10.jar) 
>   UCHIJAAAA   Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) 
>   UCHIJAAAA   ForgeMicroblock{1.2.0.347} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
>   UCHIJAAAA   McMultipart{1.2.0.347} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
>   UCHIJAAAA   denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
>   UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
>   UCHIJAAAA   JustAnotherSpawner{0.17.4} [Just Another Spawner](JustAnotherSpawner-0.17.4.jar) 
>   CoFHCore: -[1.7.10]3.1.3-327
>   ThermalFoundation: -[1.7.10]1.2.5-115
>   Mantle Environment: Environment healthy.
>   ThermalExpansion: -[1.7.10]4.1.4-247
>   TConstruct Environment: Environment healthy.
>   ThermalDynamics: -[1.7.10]1.2.0-171
>   Profiler Position: N/A (disabled)
>   Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   Player Count: 0 / 5; []
>   Is Modded: Definitely; Server brand changed to 'fml,forge'
>   Type: Dedicated Server (map_server.txt)

**Comment by WhiskyTangoFawks** [comment]
I'm afraid I'm not supporting the 1.7.10 version anymore, as I've moved completely to 1.10, but it does look like there's an incompatability with buildcraft.

**Comment by Labna** [comment]
Ho crap...
Thanks for the fast answer !
So for me, no quarry !
